name: Deploy work flow for Amazon ECS

on:
  pull_request:
    branches:
      - develop
    types: [closed]

env:
  AWS_REGION: ap-northeast-1
  ECS_SERVICE: friends-stg-service
  RAILS_CONTAINER_NAME: friends-stg-rails
  RAILS_TAG: 1.0.0

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Rails push to ECR
      id: build-image-rails
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$RAILS_CONTAINER_NAME:$RAILS_TAG . --no-cache
        docker tag $ECR_REGISTRY/$RAILS_CONTAINER_NAME:$RAILS_TAG $ECR_REGISTRY/$RAILS_CONTAINER_NAME:latest
        docker push $ECR_REGISTRY/$RAILS_CONTAINER_NAME:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --service $ECS_SERVICE --cluster friends-stg-cluster --force-new-deployment